#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Foobar',1.0);

$app->add(new SpeakCommand);
$app->add(new Password);

$app->run();
